### ISSUE TITLE
Crazy names from unprojected map units with RelPos()

### ISSUE THREAD

**Issue by benjaminmisiuk** [ailich/MultiscaleDTM#67]
Appending the map units to the layer names using `include_scale = TRUE` when the `shape` is `"circle"` or `"annulus"` and `unit = "map"` is super helpful... for projected data. For unprojected data, this produces some crazy names.
```
r <- rast(volcano, extent= ext(2667400, 2667400 + ncol(volcano)*10, 6478700, 6478700 + nrow(volcano)*10), crs = "EPSG:27200")
r <- project(r, 'epsg:4326')
rp <- RelPos(r, shape = 'circle', unit = 'map', include_scale = TRUE)
names(rp)
#[1] "rpos_9.83707799516553e-05MU"
```
Is it possible to round projected layer names (e.g., to two sig figs)?

**Comment by ailich** [comment]
@benjaminmisiuk that's not a bug but is not a pretty layer name either. Since the map units here are degrees, and you have the radius set at the default (i.e. 1 cell) the radius in map units is the resolution of the raster which each cell is 9.837078e-05 degrees x 9.837078e-05 9.837078e-05. In `RelPos` I did add the capability to have `include_scale` be a character so a workflow like that could work. This was added since `RelPos` can take custom windows which I don't know how the user would want to define the scale, but I guess it could be useful here to make layer names prettier. I could also add that functionality to other functions (e.g. the other Relative Position  functions and VRM) if you'd think it''d be useful. There's also just always the option to set `include_scale=FALSE` and then append your scale using the `names` function.

``` r
library(MultiscaleDTM)
#> Loading required package: terra
#> Warning: package 'terra' was built under R version 4.2.2
#> terra 1.7.2

r <- rast(volcano, extent= ext(2667400, 2667400 + ncol(volcano)*10, 6478700, 6478700 + nrow(volcano)*10), crs = "EPSG:27200")
r <- project(r, 'epsg:4326')

scale_name<- paste0(signif(terra::xres(r),1),"MUx", signif(terra::yres(r),1),"MU")
scale_name
#> [1] "1e-04MUx1e-04MU"

rp1 <- RelPos(r, shape = 'circle', unit = 'map', include_scale = FALSE)
names(rp1)<- paste(names(rp1), scale_name, sep="_")
names(rp1)
#> [1] "rpos_1e-04MUx1e-04MU"

rp2 <- RelPos(r, shape = 'circle', unit = 'map', include_scale = scale_name)
names(rp2)
#> [1] "rpos_1e-04MUx1e-04MU"
```

<sup>Created on 2023-02-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ailich** [comment]
@benjaminmisiuk I added the ability to specify `include_scale` as a numeric for `RelPos` where you're setting the number of significant digits to round to, and can add that to other functions later on. Now you can do

``` r
library(MultiscaleDTM)
#> Loading required package: terra
#> Warning: package 'terra' was built under R version 4.2.2
#> terra 1.7.2
r <- rast(volcano, extent= ext(2667400, 2667400 + ncol(volcano)*10, 6478700, 6478700 + nrow(volcano)*10), crs = "EPSG:27200")
r <- project(r, 'epsg:4326')
rp <- RelPos(r, shape = 'circle', unit = 'map', include_scale = 2)
names(rp)
#> [1] "rpos_9.8e-05MU"
```

<sup>Created on 2023-02-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by benjaminmisiuk** [comment]
Nice solution. Thanks.

**Comment by ailich** [comment]
There are conflicts if `unit` is specified in the creation of `w` but also in in `RelPos`. Map units end up being used but layer name does not indicate that if `include_scale` is numeric.

**Comment by ailich** [comment]
Now you cannot specify units both in `w` and `unit`. 50becfef01ab8829f363751aa567eb9b4c1bce2d

``` r
library(MultiscaleDTM)
#> Loading required package: terra
#> Warning: package 'terra' was built under R version 4.2.2
#> terra 1.7.2

r <- rast(volcano, extent= ext(2667400, 2667400 + ncol(volcano)*10, 6478700, 6478700 + nrow(volcano)*10), crs = "EPSG:27200")
r <- project(r, 'epsg:4326')

RelPos(r, w= circle_window(radius = max(res(r)), unit = "map", resolution = res(r)), shape = 'circle', include_scale = TRUE) |> names()
#> [1] "rpos_9.83707799516553e-05MU"
RelPos(r, radius = max(res(r)), unit = "map", shape = 'circle', include_scale = TRUE) |> names()
#> [1] "rpos_9.83707799516553e-05MU"

RelPos(r, circle_window(radius = max(res(r)), unit = "map", resolution = res(r)), shape = 'circle', include_scale = 2) |> names()
#> [1] "rpos_9.8e-05MU"
RelPos(r, radius = max(res(r)), unit = "map", shape = 'circle', include_scale = 2) |> names()
#> [1] "rpos_9.8e-05MU"

RelPos(r, circle_window(radius = 1, unit = "cell"), shape = 'circle', include_scale = TRUE) |> names()
#> [1] "rpos_1"
RelPos(r, radius = 1, unit = "cell", shape = 'circle', include_scale = TRUE) |> names()
#> [1] "rpos_1"

RelPos(r, circle_window(radius = 1, unit = "cell"), shape = 'circle', include_scale = 2) |> names()
#> [1] "rpos_1"
RelPos(r, radius = 1, unit = "cell", shape = 'circle', include_scale = 2) |> names()
#> [1] "rpos_1"


RelPos(r, circle_window(radius = 1, unit = "cell"), shape = 'circle', unit= "map", include_scale = TRUE) #This should throe an error
#> Error in RelPos(r, circle_window(radius = 1, unit = "cell"), shape = "circle", : Error: unit be NULL or NA if no radius is specified
```

<sup>Created on 2023-02-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by benjaminmisiuk** [comment]
Awesome, thank you.

**Comment by benjaminmisiuk** [comment]
Just a note @ailich that I think this causes the defaults to fail at [line 199](https://github.com/ailich/MultiscaleDTM/blob/24df2d4e12a0e2b8d57ce1e5b78653da7b89076d/R/RelPos.R#L199):
```
r <- rast(volcano, extent= ext(2667400, 2667400 + ncol(volcano)*10, 6478700, 6478700 + nrow(volcano)*10), crs = "EPSG:27200")

RelPos(r)
#Error in if (unit == "map" & (!shape %in% c("circle", "annulus"))) { : 
# missing value where TRUE/FALSE needed
```
